# https://github.com/Aider-AI/aider/blob/028257480b2eeaeb0b6d5e27c2bcde08e4b8ba86/aider/website/docs/config/adv-model-settings.md?plain=1#L63
# https://github.com/Aider-AI/aider/blob/028257480b2eeaeb0b6d5e27c2bcde08e4b8ba86/aider/resources/model-settings.yml#L960-L973
# https://github.com/Aider-AI/aider/blob/028257480b2eeaeb0b6d5e27c2bcde08e4b8ba86/aider/website/docs/llms/openrouter.md?plain=1#L42
- name: openrouter/google/gemini-2.5-pro-preview-03-25
  edit_format: diff-fenced
  use_repo_map: true
  weak_model_name: openrouter/google/gemini-2.0-flash-001
