#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
# yabai -m config                                 \
#     external_bar                 off:40:0       \
#     menubar_opacity              1.0            \
#     mouse_follows_focus          off            \
#     focus_follows_mouse          off            \
#     display_arrangement_order    default        \
#     window_origin_display        default        \
#     window_placement             second_child   \
#     window_zoom_persist          on             \
#     window_shadow                on             \
#     window_animation_duration    0.0            \
#     window_animation_easing      ease_out_circ  \
#     window_opacity_duration      0.0            \
#     active_window_opacity        1.0            \
#     normal_window_opacity        0.90           \
#     window_opacity               off            \
#     insert_feedback_color        0xffd75f5f     \
#     split_ratio                  0.50           \
#     split_type                   auto           \
#     auto_balance                 off            \
#     top_padding                  12             \
#     bottom_padding               12             \
#     left_padding                 12             \
#     right_padding                12             \
#     window_gap                   06             \
#     layout                       bsp            \
#     mouse_modifier               fn             \
#     mouse_action1                move           \
#     mouse_action2                resize         \
#     mouse_drop_action            swap

# If you always want windows to be fullscreen you can just use the `stack` layout instead of `bsp`.
# https://github.com/koekeishiya/skhd/issues/273#issuecomment-1574851997
# https://github.com/koekeishiya/yabai/discussions/1038#discussioncomment-1591562
# bsp, float, stack
yabai -m config layout stack

# When focusing a window, put the mouse at its center
# https://github.com/yqrashawn/yqdotfiles/blob/master/modules/yqrashawn/home-manager/dotfiles/yabai/yabairc
# yabai -m config mouse_follows_focus on

# Balance the window tree upon change, so that all windows occupy the same area.
yabai -m config auto_balance on

# app auto focus on open
# https://github.com/zegervdv/homebrew-zathura/issues/62#issuecomment-1413968157
for app in "zathura" \
  "Karabiner-Elements"; do
  yabai -m signal --add app="^${app}$" event=window_created action="~/.config/yabai/focus_last_window_id.zsh ${app}"
done

# https://github.com/yqrashawn/yqdotfiles/blob/master/modules/yqrashawn/home-manager/dotfiles/yabai/rules
yabai -m rule --add app="^Emacs$" title="^(Emacs Everywhere|edit - )" manage=off
yabai -m rule --add app="^Finder$" title="^/Volumes/" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
# https://github.com/macstewart/dotfiles/blob/dbd0d7bda2199bae17d1bd1637aafc35cc776470/dot_config/yabai/executable_yabairc.tmpl#L46
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Settings|Move|Preferences|Breakpoints|Select Methods to Implement|Harpoon|Evaluate)$" manage=off
# yabai -m rule --add app="^KeePassXC$" title="^(Unlock Database - )" manage=off

# TODO not work if: open Filder (no visible window of Filder before) -> cmd+f -> cmd+w -> cmd+w
# If no window is focused after a window is destroyed or minimized, focus the window under the cursor
# useful when close Finder.app's last window
# https://github.com/z20240/yabai/blob/master/scripts/windowFocusOnDestroy.sh
# https://github.com/koekeishiya/yabai/issues/485#issuecomment-617953545
# https://github.com/koekeishiya/dotfiles/blob/master/yabai/yabairc
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq '.[0].id') &> /dev/null"
# yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq '.[0].id') &> /dev/null; fi"
yabai -m signal --add event=window_minimized active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq '.[0].id') &> /dev/null"

# restart to adjust for display removals or additions
# https://github.com/dgrebb/macos-customs/blob/ce2099cd1caa5a8a24e0ee6ca96538a777a07b47/.config/yabai/_signals.sh#L12
# https://github.com/deferred/dotfiles/blob/8fb702437d59a9fb4f4a7b416824cd4b2ff02e1c/private_dot_config/yabai/executable_yabairc#L45
# https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#quickly-restart-the-yabai-launch-agent
yabai -m signal --add event=display_added action="sleep 1; brew services stop felixkratz/formulae/borders; yabai --restart-service"
yabai -m signal --add event=display_removed action="sleep 1; brew services stop felixkratz/formulae/borders; yabai --restart-service"

# input source auto switch can be done here
# https://github.com/Juggeli/nixos-config/blob/9524faf66ebbcc168319fb062713a8ad06304e9e/modules/darwin/desktop/yabai.nix#L81
# yabai -m signal --add event=window_focused action="keyboardSwitcher select 'U.S.'" app="kitty"

# borders for bsp layout only, not for stack. see `~/.config/karabiner.edn` file
# https://github.com/FelixKratz/JankyBorders#bootstrap-with-yabai
# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."

# TODO
# https://github.com/koekeishiya/dotfiles/blob/master/yabai/yabairc
# https://github.com/FelixKratz/dotfiles/blob/master/.config/yabai/yabairc
# https://github.com/AdamWagner/stackline
