# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
