#!/bin/bash

FILE=$1

if [[ $(file --mime-encoding -b $FILE) == "binary" ]]; then
  # file --mime $FILE
  file $FILE
else
  # bat --color=always --wrap=never --paging=never --style=plain $FILE
  pygmentize -O style=one-dark -f console256 -g $FILE
fi
