# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml
# https://yazi-rs.github.io/docs/configuration/keymap

[manager]

prepend_keymap = [
  # https://yazi-rs.github.io/docs/tips/#dropping-to-shell
  # Dropping to the shell
  { on = "<C-s>", run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

  # https://yazi-rs.github.io/docs/tips/#smart-enter
  # https://yazi-rs.github.io/docs/faq#why-separate-open-enter
  { on = "l", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },

  # # https://yazi-rs.github.io/docs/tips#navigation-wraparound
  # { on = "k", run = "plugin --sync arrow --args=-1", desc = "Move cursor up (wraparound)" },
  # { on = "j", run = "plugin --sync arrow --args=1", desc = "Move cursor down (wraparound)" },

  # # https://yazi-rs.github.io/docs/tips#parent-arrow
  # { on = "K", run = "plugin --sync parent-arrow --args=-1", desc = "Navigation in the parent directory without leaving the CWD" },
  # { on = "J", run = "plugin --sync parent-arrow --args=1", desc = "Navigation in the parent directory without leaving the CWD" },

  { on = "<C-o>", run = "back", desc = "Go back to the previous directory" },
  { on = "<Tab>", run = "forward", desc = "Go forward to the next directory (<C-i>)" },
  { on = "<Left>", run = "back", desc = "Go back to the previous directory" },
  { on = "<Right>", run = "forward", desc = "Go forward to the next directory" },

  # https://github.com/dedukun/bookmarks.yazi
  { on = "m", run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark" },
  { on = "'", run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark" },
]

append_keymap = [
  # https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },

  # https://yazi-rs.github.io/docs/configuration/keymap#manager.shell
  { on = "e", run = 'shell "${EDITOR:=vi} \"$@\"" --block --confirm', desc = "Edit the selected files use $EDITOR" },
  { on = "E", run = 'shell "open -a /Applications/Emacs.app \"$@\"" --confirm', desc = "Edit the selected files use Emacs.app" },

  { on = "<Backspace>", run = "quit", desc = "Exit the process" },

  # { on = [
  #   "g",
  #   "z",
  # ], run = "cd ~/.local/share/chezmoi", desc = "Go to the chezmoi source directory" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },

  # https://github.com/dedukun/bookmarks.yazi
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
  { on = [
    "b",
    "D",
  ], run = "plugin bookmarks --args=delete_all", desc = "Delete all bookmarks" },

  # Linemode
  { on = [
    "g",
    "m",
    "s",
  ], run = "linemode size", desc = "Set linemode to size" },
  { on = [
    "g",
    "m",
    "p",
  ], run = "linemode permissions", desc = "Set linemode to permissions" },
  { on = [
    "g",
    "m",
    "c",
  ], run = "linemode ctime", desc = "Set linemode to ctime" },
  { on = [
    "g",
    "m",
    "m",
  ], run = "linemode mtime", desc = "Set linemode to mtime" },
  { on = [
    "g",
    "m",
    "o",
  ], run = "linemode owner", desc = "Set linemode to owner" },
  { on = [
    "g",
    "m",
    "n",
  ], run = "linemode none", desc = "Set linemode to none" },
]

[tasks]

append_keymap = [{ on = ["g", "?"], run = "help", desc = "Open help" }]

[select]

append_keymap = [{ on = ["g", "?"], run = "help", desc = "Open help" }]

[input]

prepend_keymap = [
  # # https://yazi-rs.github.io/docs/tips/#close-input-by-esc
  # # Close input by once `Esc` press (without entering Vi mode)
  # { on = "<Esc>", run = 'close', desc = "Cancel input" },
]

append_keymap = [{ on = ["g", "?"], run = "help", desc = "Open help" }]

[completion]

append_keymap = [{ on = ["g", "?"], run = "help", desc = "Open help" }]

[help]

append_keymap = [
  { on = "<Backspace>", run = "close", desc = "Exit the process" },
]
