# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml
# https://yazi-rs.github.io/docs/configuration/keymap

[manager]

prepend_keymap = [
  # https://yazi-rs.github.io/docs/tips/#dropping-to-shell
  # Dropping to the shell <C-s>
  { on = "s", run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

  # https://yazi-rs.github.io/docs/tips/#smart-enter
  # https://yazi-rs.github.io/docs/faq#why-separate-open-enter
  { on = "l", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },

  # # https://yazi-rs.github.io/docs/tips#navigation-wraparound
  # { on = "k", run = "plugin --sync arrow --args=-1", desc = "Move cursor up (wraparound)" },
  # { on = "j", run = "plugin --sync arrow --args=1", desc = "Move cursor down (wraparound)" },

  # # https://yazi-rs.github.io/docs/tips#parent-arrow
  # { on = "K", run = "plugin --sync parent-arrow --args=-1", desc = "Navigation in the parent directory without leaving the CWD" },
  # { on = "J", run = "plugin --sync parent-arrow --args=1", desc = "Navigation in the parent directory without leaving the CWD" },

  { on = "<C-o>", run = "back", desc = "Go back to the previous directory" },
  { on = "<Tab>", run = "forward", desc = "Go forward to the next directory (<C-i>)" },
  { on = "<Left>", run = "back", desc = "Go back to the previous directory" },
  { on = "<Right>", run = "forward", desc = "Go forward to the next directory" },

  # https://github.com/dedukun/bookmarks.yazi
  { on = "m", run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark" },
  { on = "'", run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark" },

  { on = "<Esc>", run = [
    "escape",
    "unyank",
  ], desc = "Exit visual mode, clear selected, or cancel search, or cancel yank status" },

  # Operation
  # { on = [
  #   "y",
  #   "y",
  # ], run = "yank", desc = "Yank selected files (copy)" }, # TODO: `y` in visual mode
  # https://github.com/orhnk/system-clipboard.yazi
  { on = "Y", run = "plugin system-clipboard", desc = "Cancel the yank status" },
  # { on = [
  #   "d",
  #   "d",
  # ], run = "remove", desc = "Trash selected files" }, # TODO: `d` in visual mode
  # swap : and ; by karabiner
  { on = ":", run = "shell --interactive", desc = "Run a shell command" },
  { on = ";", run = "shell --block --interactive", desc = "Run a shell command (block until finishes)" },

  # Selection
  { on = ",", run = [
    "select --state=none",
    "arrow 1",
  ], desc = "Toggle the current selection state" },

  # Leader key
  { on = [
    "<Space>",
    "<Space>",
  ], run = "search fd", desc = "Search files by name using fd" },
  # TODO: S
  { on = [
    "<Space>",
    "/",
  ], run = "search rg", desc = "Search files by content using ripgrep" },
  { on = [
    "<Space>",
    "<Backspace>",
  ], run = "quit", desc = "Exit the process" },
]

append_keymap = [
  # https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },

  # https://yazi-rs.github.io/docs/configuration/keymap#manager.shell
  { on = "e", run = 'shell "${EDITOR:=vi} \"$@\"" --block --confirm', desc = "Edit the selected files use $EDITOR" },
  { on = "E", run = 'shell "open -a /Applications/Emacs.app \"$@\"" --confirm', desc = "Edit the selected files use Emacs.app" },

  { on = "<Backspace>", run = "close", desc = "Close the current tab, or quit if it is last tab" },

  # TODO: since we have bookmarks: gh gc gd
  # { on = [
  #   "g",
  #   "z",
  # ], run = "cd ~/.local/share/chezmoi", desc = "Go to the chezmoi source directory" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },

  # TODO: .
  { on = [
    "g",
    ".",
  ], run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

  # https://github.com/dedukun/bookmarks.yazi
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
  { on = [
    "b",
    "D",
  ], run = "plugin bookmarks --args=delete_all", desc = "Delete all bookmarks" },

  # Linemode
  { on = [
    "g",
    "m",
    "s",
  ], run = "linemode size", desc = "Set linemode to size" },
  { on = [
    "g",
    "m",
    "p",
  ], run = "linemode permissions", desc = "Set linemode to permissions" },
  { on = [
    "g",
    "m",
    "c",
  ], run = "linemode ctime", desc = "Set linemode to ctime" },
  { on = [
    "g",
    "m",
    "m",
  ], run = "linemode mtime", desc = "Set linemode to mtime" },
  { on = [
    "g",
    "m",
    "o",
  ], run = "linemode owner", desc = "Set linemode to owner" },
  { on = [
    "g",
    "m",
    "n",
  ], run = "linemode none", desc = "Set linemode to none" },

  # Sorting
  { on = [
    "g",
    "s",
    "m",
  ], run = [
    "sort modified --reverse=no",
    "linemode mtime",
  ], desc = "Sort by modified time" },
  { on = [
    "g",
    "s",
    "M",
  ], run = [
    "sort modified --reverse",
    "linemode mtime",
  ], desc = "Sort by modified time (reverse)" },
  { on = [
    "g",
    "s",
    "c",
  ], run = [
    "sort created --reverse=no",
    "linemode ctime",
  ], desc = "Sort by created time" },
  { on = [
    "g",
    "s",
    "C",
  ], run = [
    "sort created --reverse",
    "linemode ctime",
  ], desc = "Sort by created time (reverse)" },
  { on = [
    "g",
    "s",
    "e",
  ], run = "sort extension --reverse=no", desc = "Sort by extension" },
  { on = [
    "g",
    "s",
    "E",
  ], run = "sort extension --reverse", desc = "Sort by extension (reverse)" },
  { on = [
    "g",
    "s",
    "a",
  ], run = "sort alphabetical --reverse=no", desc = "Sort alphabetically" },
  { on = [
    "g",
    "s",
    "A",
  ], run = "sort alphabetical --reverse", desc = "Sort alphabetically (reverse)" },
  { on = [
    "g",
    "s",
    "n",
  ], run = "sort natural --reverse=no", desc = "Sort naturally" },
  { on = [
    "g",
    "s",
    "N",
  ], run = "sort natural --reverse", desc = "Sort naturally (reverse)" },
  { on = [
    "g",
    "s",
    "s",
  ], run = [
    "sort size --reverse=no",
    "linemode size",
  ], desc = "Sort by size" },
  { on = [
    "g",
    "s",
    "S",
  ], run = [
    "sort size --reverse",
    "linemode size",
  ], desc = "Sort by size (reverse)" },
  { on = [
    "g",
    "s",
    "r",
  ], run = "sort random --reverse=no", desc = "Sort randomly" },
]

[tasks]

append_keymap = [{ on = ["g", "?"], run = "help", desc = "Open help" }]

[select]

append_keymap = [{ on = ["g", "?"], run = "help", desc = "Open help" }]

[input]

prepend_keymap = [
  # # https://yazi-rs.github.io/docs/tips/#close-input-by-esc
  # # Close input by once `Esc` press (without entering Vi mode)
  # { on = "<Esc>", run = 'close', desc = "Cancel input" },
]

append_keymap = [
  { on = ["g", "?"], run = "help", desc = "Open help" },

  # Line-wise movement
  { on = "H", run = "move -999", desc = "Move to the BOL" },
  { on = "L", run = "move 999", desc = "Move to the EOL" },
]

[completion]

append_keymap = [{ on = ["g", "?"], run = "help", desc = "Open help" }]

[help]

append_keymap = [
  { on = "<Backspace>", run = "close", desc = "Exit the process" },
]
