# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
# https://yazi-rs.github.io/docs/configuration/keymap
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
  # https://yazi-rs.github.io/docs/tips/#dropping-to-shell
  { on = "s", run = 'shell "$SHELL" --block', desc = "Open shell here" },
  # { on = "s", run = 'shell fish --block', desc = "Open shell here" },

  # https://yazi-rs.github.io/docs/tips/#smart-enter
  # https://yazi-rs.github.io/docs/faq#why-separate-open-enter
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

  # disable wraparound navigation
  { on = "k", run = "arrow -1", desc = "Previous file" },
  { on = "j", run = "arrow 1", desc = "Next file" },

  # # https://yazi-rs.github.io/docs/tips#parent-arrow
  # { on = "K", run = "plugin parent-arrow -1", desc = "Navigation in the parent directory without leaving the CWD" },
  # { on = "J", run = "plugin parent-arrow 1", desc = "Navigation in the parent directory without leaving the CWD" },

  # Tabs
  # { on = "J", run = "tab_switch 1 --relative", desc = "Switch to next tab" },
  # { on = "K", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
  { on = "<Down>", run = "tab_switch 1 --relative", desc = "Switch to next tab" },
  { on = "<Up>", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
  { on = [
    "g",
    "t",
  ], run = "tab_switch 1 --relative", desc = "Switch to next tab" },
  { on = [
    "g",
    "T",
  ], run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
  { on = "[", run = "tab_swap -1", desc = "Swap current tab with previous tab" },
  { on = "]", run = "tab_swap 1", desc = "Swap current tab with next tab" },

  # Seeking
  { on = "<C-b>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-f>", run = "seek 5", desc = "Seek down 5 units in the preview" },

  { on = "<C-o>", run = "back", desc = "Back to previous directory" },
  { on = "<Tab>", run = "forward", desc = "Forward to next directory (<C-i>)" },
  { on = "<Left>", run = "back", desc = "Back to previous directory" },
  { on = "<Right>", run = "forward", desc = "Forward to next directory" },

  # Spotting
  { on = [
    "g",
    "k",
  ], run = "spot", desc = "Spot hovered file" },

  # Goto
  { on = [
    "c",
    "d",
  ], run = "cd --interactive", desc = "Jump interactively" },

  # Copy
  { on = [
    "c",
    "D",
  ], run = "copy dirname", desc = "Copy the directory path" },
  { on = [
    "c",
    "n",
  ], run = "noop" },
  { on = [
    "c",
    "N",
  ], run = "copy name_without_ext", desc = "Copy the filename without extension" },

  # https://github.com/dedukun/bookmarks.yazi
  # h: ~
  # d: ~/Downloads
  # c: ~/.local/share/chezmoi/dot_config
  # C: ~/.config
  # n: ~/.local/share/chezmoi/dot_config/nvim
  # N: ~/.config/nvim
  # l: ~/.local/share/nvim/lazy/LazyVim
  # z: ~/.local/share/chezmoi
  { on = "m", run = "plugin bookmarks save", desc = "Save current position as a bookmark" },
  { on = "'", run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
  { on = [
    "g",
    "h",
  ], run = "noop" },
  { on = [
    "g",
    "c",
  ], run = "noop" },
  { on = [
    "g",
    "d",
  ], run = "noop" },

  { on = "<Esc>", run = [
    "escape",
    "unyank",
  ], desc = "Exit visual mode, clear selected, or cancel search, or cancel yank status" },

  # Operation
  # { on = [
  #   "y",
  #   "y",
  # ], run = "yank", desc = "Yank selected files (copy)" }, # TODO: `y` in visual mode
  # alternative: https://github.com/orhnk/system-clipboard.yazi
  { on = "<C-y>", run = 'shell --block -- cb copy "$@"', desc = "Yank to clipboard" }, # candidates: Y <C-y> gy
  { on = "<C-p>", run = "shell --block -- cb paste", desc = "Paste from clipboard" },  # candidates: <C-p> gp
  # { on = [
  #   "d",
  #   "d",
  # ], run = "remove", desc = "Trash selected files" }, # TODO: `d` in visual mode
  # swap : and ; by karabiner
  { on = ":", run = "shell --interactive", desc = "Run a shell command" },
  { on = ";", run = "shell --block --interactive", desc = "Run a shell command (block until finishes)" },

  { on = "r", run = [
    "rename --cursor=before_ext",
    "input:escape",
  ], desc = "Rename selected file(s)" },
  { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
  { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },

  # Toggle
  { on = ",", run = [
    "toggle",
    "arrow 1",
  ], desc = "Toggle the current selection state" },

  # Leader key
  { on = [
    "<Space>",
    "<Space>",
  ], run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  { on = [
    "<Space>",
    "f",
    "f",
  ], run = "search --via=fd", desc = "Search files by name via fd" },
  # TODO: S
  { on = [
    "<Space>",
    "/",
  ], run = "search --via=rg", desc = "Search files by content via ripgrep" },
  # https://yazi-rs.github.io/docs/tips/#macos-quick-look
  { on = [
    "<Space>",
    ",",
  ], run = 'shell -- qlmanage -p "$@"', desc = "Macos Quick Look" },
  { on = [
    "<Space>",
    "<Backspace>",
  ], run = "quit", desc = "Exit the process" },
  { on = [
    "c",
    "c",
  ], run = "noop" },
  { on = [
    "<Space>",
    "f",
    "y",
  ], run = "copy path", desc = "Copy the file path" },
  { on = [
    "c",
    "f",
  ], run = "noop" },
  { on = [
    "<Space>",
    "f",
    "Y",
  ], run = "copy filename", desc = "Copy the filename" },
  # https://github.com/yazi-rs/plugins/tree/main/mount.yazi
  { on = [
    "<Space>",
    "f",
    "M",
  ], run = "plugin mount", desc = "Mount Manager" },
  { on = [
    "<Space>",
    "f",
    "d",
  ], run = "shell --block -- diff -u $1 $0 | delta --paging always", desc = "Diff the selected with the hovered file" },
  # https://github.com/yazi-rs/plugins/tree/main/diff.yazi
  { on = [
    "<Space>",
    "f",
    "D",
  ], run = [
    "plugin diff",
    "shell --block -- sleep 0.05 && (command -v pbpaste >/dev/null && pbpaste || termux-clipboard-get) | delta",
  ], desc = "Diff the selected with the hovered file" },
  { on = [
    "<Space>",
    "g",
    "g",
  ], run = "shell --block lazygit", desc = "Lazygit" },
  { on = [
    "<Space>",
    "g",
    "f",
  ], run = 'shell --block -- lazygit -f "$0"', desc = "Lazygit Current File History" },
  { on = [
    "<Space>",
    "g",
    "l",
  ], run = 'shell --block -- lazygit log', desc = "Lazygit Log" },
  { on = [
    "<Space>",
    "g",
    "s",
  ], run = 'plugin vcs-files', desc = "Git changed files" },
  { on = [
    "<Space>",
    "<Tab>",
    "<Tab>",
  ], run = "tab_create --current", desc = "Create a new tab with CWD" },
  { on = [
    "<Space>",
    "<Tab>",
    "d",
  ], run = "close", desc = "Close the current tab, or quit if it is last tab" },
]

append_keymap = [
  # https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },

  # https://yazi-rs.github.io/docs/configuration/keymap#manager.shell
  { on = "e", run = 'shell --block -- ${EDITOR:=vi} "$@"', desc = "Edit the selected files use $EDITOR" },
  # { on = "E", run = 'shell -- open -a /Applications/Emacs.app "$@"', desc = "Edit the selected files use Emacs.app" },

  { on = "<Backspace>", run = "close", desc = "Close the current tab, or quit if it is last tab" },

  # https://github.com/yazi-rs/plugins/tree/main/zoom.yazi
  { on = "+", run = "plugin zoom 1", desc = "Zoom in hovered file" },
  { on = "=", run = "plugin zoom 1", desc = "Zoom in hovered file" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out hovered file" },

  # TODO: cc A
  # https://github.com/hankertrix/augment-command.yazi
  # https://github.com/hankertrix/Dotfiles/blob/80c1948cc4aea98c89dd18ba8a92aa4f48499077/.config/yazi/keymap.toml#L219
  { on = "I", run = "rename --cursor=start", desc = "Rename file at the start of the file name" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },

  # TODO: .
  { on = [
    "g",
    ".",
  ], run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

  # # https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/yazi-keymappings.md#define-a-keymap-in-yazis-config-1
  # # Augment https://yazi-rs.github.io/docs/tips/#cd-to-git-root
  # # go to the nvim cwd when neovim is open, and to the git root when it is not
  # { on = [
  #   "g",
  #   "r",
  # ], run = 'shell -- ya emit cd "${NVIM_CWD:-$(git rev-parse --show-toplevel 2>/dev/null)}"', desc = "cd to nvim cwd / git root" },
  { on = [
    "g",
    "r",
  ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "cd to git root" },

  # https://github.com/dedukun/bookmarks.yazi
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
  { on = [
    "b",
    "D",
  ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks" },

  # https://github.com/yazi-rs/plugins/tree/main/chmod.yazi
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },

  # Linemode
  { on = [
    "g",
    "m",
    "s",
  ], run = "linemode size", desc = "Linemode: size" },
  { on = [
    "g",
    "m",
    "p",
  ], run = "linemode permissions", desc = "Linemode: permissions" },
  { on = [
    "g",
    "m",
    "b",
  ], run = "linemode btime", desc = "Linemode: btime" },
  { on = [
    "g",
    "m",
    "m",
  ], run = "linemode mtime", desc = "Linemode: mtime" },
  { on = [
    "g",
    "m",
    "o",
  ], run = "linemode owner", desc = "Linemode: owner" },
  { on = [
    "g",
    "m",
    "n",
  ], run = "linemode none", desc = "Linemode: none" },

  # Sorting
  { on = [
    "g",
    "s",
    "m",
  ], run = [
    "sort mtime --reverse=no",
    "linemode mtime",
  ], desc = "Sort by modified time" },
  { on = [
    "g",
    "s",
    "M",
  ], run = [
    "sort mtime --reverse",
    "linemode mtime",
  ], desc = "Sort by modified time (reverse)" },
  { on = [
    "g",
    "s",
    "b",
  ], run = [
    "sort btime --reverse=no",
    "linemode btime",
  ], desc = "Sort by birth time" },
  { on = [
    "g",
    "s",
    "B",
  ], run = [
    "sort btime --reverse",
    "linemode btime",
  ], desc = "Sort by birth time (reverse)" },
  { on = [
    "g",
    "s",
    "e",
  ], run = "sort extension --reverse=no", desc = "Sort by extension" },
  { on = [
    "g",
    "s",
    "E",
  ], run = "sort extension --reverse", desc = "Sort by extension (reverse)" },
  { on = [
    "g",
    "s",
    "a",
  ], run = "sort alphabetical --reverse=no", desc = "Sort alphabetically" },
  { on = [
    "g",
    "s",
    "A",
  ], run = "sort alphabetical --reverse", desc = "Sort alphabetically (reverse)" },
  { on = [
    "g",
    "s",
    "n",
  ], run = "sort natural --reverse=no", desc = "Sort naturally" },
  { on = [
    "g",
    "s",
    "N",
  ], run = "sort natural --reverse", desc = "Sort naturally (reverse)" },
  { on = [
    "g",
    "s",
    "s",
  ], run = [
    "sort size --reverse=no",
    "linemode size",
  ], desc = "Sort by size" },
  { on = [
    "g",
    "s",
    "S",
  ], run = [
    "sort size --reverse",
    "linemode size",
  ], desc = "Sort by size (reverse)" },
  { on = [
    "g",
    "s",
    "r",
  ], run = "sort random --reverse=no", desc = "Sort randomly" },
]

[tasks]

prepend_keymap = [
  { on = "k", run = "arrow -1", desc = "Previous task" },
  { on = "j", run = "arrow 1", desc = "Next task" },
]

append_keymap = [
  { on = "<Backspace>", run = "close", desc = "Close task manager" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },
]

[spot]

prepend_keymap = [
  { on = "k", run = "arrow -1", desc = "Previous line" },
  { on = "j", run = "arrow 1", desc = "Next line" },

  # Copy
  { on = ["c", "c"], run = "noop" },
  # { on = ["y", "y"], run = "copy cell", desc = "Copy selected cell" },
  { on = "y", run = "copy cell", desc = "Copy selected cell" },
]

append_keymap = [
  { on = "<Backspace>", run = "close", desc = "Close the spot" },
  { on = [
    "g",
    "k",
  ], run = "close", desc = "Close the spot" },

  { on = [
    "g",
    "g",
  ], run = "arrow top", desc = "Go to top" },
  { on = "G", run = "arrow bot", desc = "Go to bottom" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },
]

[pick]

prepend_keymap = [
  { on = "k", run = "arrow -1", desc = "Previous option" },
  { on = "j", run = "arrow 1", desc = "Next option" },
]

append_keymap = [
  { on = "<Backspace>", run = "close", desc = "Cancel pick" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },
]

[input]

prepend_keymap = [
  # # https://yazi-rs.github.io/docs/tips/#close-input-by-esc
  # # Close input by once `Esc` press (without entering Vi mode)
  # { on = "<Esc>", run = "close", desc = "Cancel input" },
]

append_keymap = [
  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },

  # Line-wise movement
  { on = "H", run = "move first-char", desc = "Move to the first non-whitespace character" },
  { on = "L", run = "move eol", desc = "Move to the EOL" },

  { on = "U", run = "redo", desc = "Redo the last operation" },
]

[confirm]

prepend_keymap = [
  { on = "k", run = "arrow -1", desc = "Previous line" },
  { on = "j", run = "arrow 1", desc = "Next line" },
]

append_keymap = [
  { on = "<Backspace>", run = "close", desc = "Cancel the confirm" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },
]

[cmp]

append_keymap = [
  { on = "<C-e>", run = "close", desc = "Cancel completion" },
  { on = "<C-y>", run = "close --submit", desc = "Submit the completion" },

  { on = "<C-k>", run = "arrow prev", desc = "Previous item" },
  { on = "<C-j>", run = "arrow next", desc = "Next item" },

  { on = [
    "g",
    "?",
  ], run = "help", desc = "Open help" },
]

[help]

prepend_keymap = [
  { on = "k", run = "arrow -1", desc = "Previous line" },
  { on = "j", run = "arrow 1", desc = "Next line" },
]

append_keymap = [
  { on = "<Backspace>", run = "close", desc = "Hide the help" },
  { on = "~", run = "close", desc = "Hide the help" },
  { on = ["g", "?"], run = "close", desc = "Hide the help" },

  # Navigation
  { on = ["g", "g"], run = "arrow top", desc = "Go to top" },
  { on = "G", run = "arrow bot", desc = "Go to bottom" },
  { on = "<C-u>", run = "arrow -50%", desc = "Move cursor up half page" },
  { on = "<C-d>", run = "arrow 50%", desc = "Move cursor down half page" },
  { on = "<C-b>", run = "arrow -100%", desc = "Move cursor up one page" },
  { on = "<C-f>", run = "arrow 100%", desc = "Move cursor down one page" },

  # Filtering
  { on = "/", run = "filter", desc = "Filter help items" },
]
