# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/theme-dark.toml
# https://yazi-rs.github.io/docs/configuration/theme
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# # https://yazi-rs.github.io/docs/faq#dont-like-nerd-fonts
# [status]
# sep_left = { open = "", close = "" }
# sep_right = { open = "", close = "" }
#
# [icon]
# globs = []
# dirs = []
# files = []
# exts = []
# conds = []

# https://github.com/yazi-rs/flavors/tree/main/catppuccin-frappe.yazi
[flavor]
dark = "catppuccin-frappe"
