# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme.toml
# https://yazi-rs.github.io/docs/configuration/theme

# # https://yazi-rs.github.io/docs/faq#dont-like-nerd-fonts
# [status]
# separator_open = ""
# separator_close = ""
#
# [icon]
# globs = []
# dirs = []
# files = []
# exts = []
# conds = []

# https://github.com/yazi-rs/flavors/tree/main/catppuccin-frappe.yazi
[flavor]
use = "catppuccin-frappe"
