# https://neovide.dev/config-file.html
# https://neovide.dev/command-line-reference.html#frame
frame = "none"

[font]
normal = ["Maple Mono NF CN", "Symbols Nerd Font Mono"]
size = 12.0

[font.features]
# +cv01
"Maple Mono NF CN" = ["+cv35", "+ss06", "+cv61", "+cv62"]
