import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { CustomEditor, type ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { truncateToWidth, visibleWidth } from "@mariozechner/pi-tui";

import {
  applyPromptHistory,
  hydratePromptHistory,
  replacePromptHistory,
} from "./prompt-history.ts";

const INSERT_PREFIX = "❯ ";
const NORMAL_PREFIX = "❮ ";
const CONTINUATION_PREFIX = "  ";
const PREFIX_WIDTH = visibleWidth(INSERT_PREFIX);
const EXTENSION_DIR =
  typeof __dirname === "string" ? __dirname : dirname(fileURLToPath(import.meta.url));
// pi's extension loader can evaluate TS via jiti, but importing pi-vim directly
// is not reliable in this extension context. We generate a tiny local wrapper
// that re-exports the globally installed pi-vim entry and import that instead.
const PI_VIM_WRAPPER = join(EXTENSION_DIR, "pi-vim.generated.ts");

function findPiVimEntry(): string {
  try {
    const npmRoot = execSync("npm root -g", { encoding: "utf-8" }).trim();
    const entry = join(npmRoot, "pi-vim", "index.ts");
    if (existsSync(entry)) return entry;
  } catch {}

  throw new Error("prompt-editor: pi-vim not found. Install with: pi install npm:pi-vim");
}

function ensurePiVimWrapper(): void {
  // Keep the generated wrapper in sync with the current global npm root so the
  // extension remains self-contained and does not require a manual setup step.
  const piVimEntry = findPiVimEntry();
  const content = `/**
 * Auto-generated by prompt-editor/index.ts.
 * Do not edit manually.
 */

export * from ${JSON.stringify(piVimEntry)};
`;

  const current = existsSync(PI_VIM_WRAPPER) ? readFileSync(PI_VIM_WRAPPER, "utf8") : null;
  if (current !== content) {
    writeFileSync(PI_VIM_WRAPPER, content);
  }
}

export default async function (pi: ExtensionAPI) {
  ensurePiVimWrapper();

  const { ModalEditor } = await import("./pi-vim.generated.ts");

  type Mode = "insert" | "normal";

  type ThinkingTheme = {
    getThinkingBorderColor?: (level: string) => ((s: string) => string) | undefined;
    fg: (color: string, text: string) => string;
  };

  type ModalEditorInstance = InstanceType<typeof ModalEditor> & {
    getModeLabel?: () => string;
    labelColorizers?: {
      insert: (s: string) => string;
      normal: (s: string) => string;
    } | null;
    borderColor?: (s: string) => string;
  };

  function findBottomBorderIndex(lines: string[]): number {
    for (let i = lines.length - 1; i >= 0; i--) {
      const stripped = lines[i]!.replace(/\x1b\[[0-9;]*m/g, "");
      if (stripped.startsWith("─")) return i;
    }
    return -1;
  }

  // Related upstream logic:
  // - https://github.com/lajarre/pi-vim/blob/3eaa60ab3ca1dfca4c3ce3661d24d8327b747842/index.ts#L2218-L2259 (ModalEditor.render + getModeLabel)
  function getRenderedModeLabel(editor: ModalEditorInstance): {
    raw: string;
    rendered: string;
  } {
    const raw =
      editor.getModeLabel?.() ?? (editor.getMode() === "insert" ? " INSERT " : " NORMAL ");
    const colorize = editor.labelColorizers
      ? editor.getMode() === "insert"
        ? editor.labelColorizers.insert
        : editor.labelColorizers.normal
      : null;

    return {
      raw,
      rendered: colorize ? colorize(raw) : raw,
    };
  }

  function getRenderedPrefix(
    colorizers: {
      insert: (s: string) => string;
      normal: (s: string) => string;
    } | null,
    mode: Mode,
    prefix: string,
  ): string {
    const colorize = colorizers
      ? mode === "insert"
        ? colorizers.insert
        : colorizers.normal
      : null;

    return colorize ? colorize(prefix) : prefix;
  }

  function applyThinkingBorderColor(
    editor: ModalEditorInstance,
    theme: ThinkingTheme | undefined,
  ): void {
    const borderColor = theme?.getThinkingBorderColor?.(pi.getThinkingLevel());
    if (borderColor) {
      editor.borderColor = borderColor;
    }
  }

  const VIM_REMAPS: Record<string, string> = {
    H: "0",
    L: "$",
    U: "\x12", // Ctrl+r
  };

  class PromptEditor extends ModalEditor {
    private readonly prefixColorizers: {
      insert: (s: string) => string;
      normal: (s: string) => string;
    } | null;

    constructor(
      tui: any,
      theme: any,
      kb: any,
      labelColorizers: {
        insert: (s: string) => string;
        normal: (s: string) => string;
      } | null,
      prefixColorizers: {
        insert: (s: string) => string;
        normal: (s: string) => string;
      } | null,
    ) {
      super(tui, theme, kb, labelColorizers);
      this.prefixColorizers = prefixColorizers;
    }

    override handleInput(data: string): void {
      if (this.getMode() === "normal") {
        // Single-key remaps (H -> 0, L -> $, U -> Ctrl+r)
        if (data in VIM_REMAPS) {
          super.handleInput(VIM_REMAPS[data]!);
          return;
        }
        // Y -> y$
        if (data === "Y") {
          super.handleInput("y");
          super.handleInput("$");
          return;
        }
        // cl -> s: pi-vim doesn't accept l as a motion for c, so we clear
        // the pending operator directly and delegate to the native s command.
        if (
          (this as unknown as { pendingOperator: string | null }).pendingOperator === "c" &&
          data === "l"
        ) {
          (this as unknown as { pendingOperator: string | null }).pendingOperator = null;
          super.handleInput("s"); // cut char + insert
          return;
        }
      }
      super.handleInput(data);
    }

    override render(width: number): string[] {
      if (width <= PREFIX_WIDTH) return super.render(width);

      // Related upstream logic:
      // - https://github.com/lajarre/pi-vim/blob/3eaa60ab3ca1dfca4c3ce3661d24d8327b747842/index.ts#L2218-L2232 (ModalEditor.render)
      // - https://github.com/badlogic/pi-mono/blob/e3fee7a511503ebe170223cd89e7631751539f25/packages/coding-agent/src/modes/interactive/components/custom-editor.ts
      //
      // Bypass ModalEditor.render() here so pi-vim does not append the mode
      // label to the last rendered line (which becomes the autocomplete list
      // during slash-command completion). We re-attach the label to the actual
      // bottom border below.
      const lines = CustomEditor.prototype.render.call(this, width - PREFIX_WIDTH) as string[];
      if (lines.length < 3) return lines;

      const bottomIdx = findBottomBorderIndex(lines);
      if (bottomIdx <= 0) return lines;

      const borderColor = this.borderColor ?? ((s: string) => s);
      const extraBorder = borderColor("─".repeat(PREFIX_WIDTH));
      const mode = this.getMode();
      const prefix = mode === "insert" ? INSERT_PREFIX : NORMAL_PREFIX;
      const renderedPrefix = getRenderedPrefix(this.prefixColorizers, mode, prefix);
      const { raw: rawLabel, rendered: renderedLabel } = getRenderedModeLabel(
        this as ModalEditorInstance,
      );
      const labelWidth = visibleWidth(rawLabel);

      // The editor body is rendered `PREFIX_WIDTH` columns narrower so wrapped
      // text accounts for the prompt prefix. We then extend the top/bottom
      // borders back to the full terminal width and prefix only the body lines.
      lines[0] = lines[0]! + extraBorder;
      if (visibleWidth(lines[bottomIdx]!) >= labelWidth) {
        lines[bottomIdx] =
          truncateToWidth(lines[bottomIdx]!, width - PREFIX_WIDTH - labelWidth, "") +
          extraBorder +
          renderedLabel;
      } else {
        lines[bottomIdx] = lines[bottomIdx]! + extraBorder;
      }

      for (let i = 1; i < bottomIdx; i++) {
        lines[i] = (i === 1 ? renderedPrefix : CONTINUATION_PREFIX) + lines[i]!;
      }

      // // Related upstream logic:
      // // - https://github.com/badlogic/pi-mono/blob/a1e107897d56292d987cecb5816979acae6fc6aa/packages/tui/src/components/editor.ts#L514-L522
      // //
      // // Editor.render() appends autocomplete rows after the bottom border. They
      // // were rendered at the narrower body width above, so shift them into the
      // // same gutter-aligned column as wrapped continuation lines.
      // for (let i = bottomIdx + 1; i < lines.length; i++) {
      //   lines[i] = CONTINUATION_PREFIX + lines[i]!;
      // }

      return lines;
    }
  }

  pi.on("session_start", (_event, ctx) => {
    const theme = ctx.ui.theme as ThinkingTheme | undefined;
    const colorizers = theme
      ? {
          insert: (s: string) => theme.fg("borderMuted", `\x1b[7m${s}\x1b[27m`),
          normal: (s: string) => theme.fg("borderAccent", `\x1b[7m${s}\x1b[27m`),
        }
      : null;
    // Prefix styling is intentionally lighter than the bottom mode label:
    // insert stays plain/default text, while normal gets only the accent fg.
    const prefixColorizers = theme
      ? {
          insert: (s: string) => s,
          normal: (s: string) => theme.fg("borderAccent", s),
        }
      : null;

    setTimeout(() => {
      // Related upstream logic:
      // - https://github.com/lajarre/pi-vim/blob/3eaa60ab3ca1dfca4c3ce3661d24d8327b747842/index.ts#L2262-L2271 (default export session_start handler)
      // - https://github.com/badlogic/pi-mono/blob/cca5a3a1a4c6db90e4c5e2e95772845c1d5a251d/packages/coding-agent/src/modes/interactive/interactive-mode.ts#L1841-L1909 (setCustomEditorComponent)
      //
      // Defer until after pi-vim's own session_start handler has installed its
      // editor, then replace it with our prompt-editor subclass. interactive-mode
      // also copies borderColor from defaultEditor during the swap, so we
      // re-apply the thinking-level border color below.
      let editor: ModalEditorInstance | undefined;

      applyPromptHistory(
        ctx,
        (history) => {
          ctx.ui.setEditorComponent((tui, editorTheme, kb) => {
            editor = new PromptEditor(
              tui,
              editorTheme,
              kb,
              colorizers,
              prefixColorizers,
            ) as ModalEditorInstance;
            hydratePromptHistory(editor, history);
            return editor;
          });

          if (editor) {
            // Must run after setEditorComponent() returns: interactive-mode
            // overwrites newEditor.borderColor during the swap.
            applyThinkingBorderColor(editor, theme);
          }
        },
        (history) => {
          if (!editor) return;
          replacePromptHistory(editor, history);
        },
      );
    }, 0);
  });
}
