import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { CustomEditor, getAgentDir, type ExtensionAPI } from "@earendil-works/pi-coding-agent";
import {
  CURSOR_MARKER,
  Key,
  matchesKey,
  truncateToWidth,
  visibleWidth,
} from "@earendil-works/pi-tui";

import {
  applyPromptHistory,
  hydratePromptHistory,
  replacePromptHistory,
} from "./prompt-history.ts";

const INSERT_PREFIX = "❯ ";
const NORMAL_PREFIX = "❮ ";
const CONTINUATION_PREFIX = "  ";
const PREFIX_WIDTH = visibleWidth(INSERT_PREFIX);
const ANSI_COLOR_RE = /\x1b\[[0-9;]*m/g;
const SOFTWARE_CURSOR_START = "\x1b[7m";
const SOFTWARE_CURSOR_RESETS = ["\x1b[0m", "\x1b[27m"] as const;
const EXTENSION_DIR =
  typeof __dirname === "string" ? __dirname : dirname(fileURLToPath(import.meta.url));
// pi's extension loader can evaluate TS via jiti, but importing pi-vim directly
// is not reliable in this extension context. We generate a tiny local wrapper
// that re-exports the pi-managed pi-vim entry and import that instead.
const PI_VIM_WRAPPER = join(EXTENSION_DIR, "pi-vim.generated.ts");

function findPiVimEntry(): string {
  // pi manages its own npm packages at <agent-dir>/npm/node_modules.
  // Use getAgentDir() to resolve the pi-managed installation (updated via
  // `pi install npm:pi-vim`).
  const entry = join(getAgentDir(), "npm", "node_modules", "pi-vim", "index.ts");
  if (existsSync(entry)) return entry;

  throw new Error("prompt-editor: pi-vim not found. Install with: pi install npm:pi-vim");
}

function ensurePiVimWrapper(): void {
  // Keep the generated wrapper in sync with the installed pi-vim version so
  // the extension remains self-contained and does not require a manual setup step.
  const piVimEntry = findPiVimEntry();
  const content = `/**
 * Auto-generated by prompt-editor/index.ts.
 * Do not edit manually.
 */

export * from ${JSON.stringify(piVimEntry)};
`;

  const current = existsSync(PI_VIM_WRAPPER) ? readFileSync(PI_VIM_WRAPPER, "utf8") : null;
  if (current !== content) {
    writeFileSync(PI_VIM_WRAPPER, content);
  }
}

// Copied from pi-vim v0.10.0 — findSoftwareCursorReset.
// https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts
function findSoftwareCursorReset(
  line: string,
  startIndex: number,
): { index: number; sequence: (typeof SOFTWARE_CURSOR_RESETS)[number] } | null {
  let firstReset: { index: number; sequence: (typeof SOFTWARE_CURSOR_RESETS)[number] } | null =
    null;

  for (const sequence of SOFTWARE_CURSOR_RESETS) {
    const index = line.indexOf(sequence, startIndex);
    if (index === -1) continue;
    if (!firstReset || index < firstReset.index) {
      firstReset = { index, sequence };
    }
  }

  return firstReset;
}

// Copied from pi-vim v0.10.0 — stripSoftwareCursorAfterMarker.
// https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts
// See also: https://github.com/earendil-works/pi/blob/d06db09a53958e485131527db25c1293f29b9367/packages/tui/src/components/editor.ts#L480-L493
function stripSoftwareCursorAfterMarker(line: string): string {
  const markerIndex = line.indexOf(CURSOR_MARKER);
  if (markerIndex === -1) return line;

  const searchStart = markerIndex + CURSOR_MARKER.length;
  const cursorStart = line.indexOf(SOFTWARE_CURSOR_START, searchStart);
  if (cursorStart === -1) return line;

  const cursorContentStart = cursorStart + SOFTWARE_CURSOR_START.length;
  const reset = findSoftwareCursorReset(line, cursorContentStart);
  if (!reset) return line;

  return (
    line.slice(0, cursorStart) +
    line.slice(cursorContentStart, reset.index) +
    line.slice(reset.index + reset.sequence.length)
  );
}

export default async function (pi: ExtensionAPI) {
  ensurePiVimWrapper();

  const { ModalEditor } = await import("./pi-vim.generated.ts");

  type Mode = "insert" | "normal";

  type ModeColorizers = Record<"insert" | "normal" | "ex", (s: string) => string>;

  type ModalEditorRuntime = {
    getMode: () => Mode;
    getModeLabel?: () => string;
    labelColorizers?: ModeColorizers | null;
    borderColor?: (s: string) => string;
    pendingExCommand: string | null;
    pendingOperator: string | null;
    addToHistory?: (text: string) => void;
    history?: string[];
    historyIndex?: number;
  };

  function findBottomBorderIndex(lines: string[]): number {
    for (let i = lines.length - 1; i >= 0; i--) {
      const stripped = lines[i]!.replace(ANSI_COLOR_RE, "");
      if (stripped.startsWith("─")) return i;
    }
    return -1;
  }

  // Related upstream logic:
  // - https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts (ModalEditor.render + getModeLabel + getModeLabelColorizer)
  function getActiveMode(editor: ModalEditorRuntime): "insert" | "normal" | "ex" {
    if (editor.pendingExCommand !== null) return "ex";
    return editor.getMode();
  }

  function getRenderedModeLabel(editor: ModalEditorRuntime): {
    raw: string;
    rendered: string;
  } {
    const raw =
      editor.getModeLabel?.() ?? (editor.getMode() === "insert" ? " INSERT " : " NORMAL ");
    const active = getActiveMode(editor);
    const colorize = editor.labelColorizers?.[active] ?? null;

    return {
      raw,
      rendered: colorize ? colorize(raw) : raw,
    };
  }

  function getRenderedPrefix(editor: ModalEditorRuntime, colorizers: ModeColorizers): string {
    const mode = editor.getMode();
    const prefix = mode === "insert" ? INSERT_PREFIX : NORMAL_PREFIX;
    const active = getActiveMode(editor);
    const colorize = colorizers[active];

    return colorize ? colorize(prefix) : prefix;
  }

  const VIM_REMAPS: Record<string, string> = {
    H: "0",
    L: "$",
    U: "\x12", // Ctrl+r
  };

  type CursorTUI = {
    getShowHardwareCursor?: () => boolean;
    setShowHardwareCursor: (enabled: boolean) => void;
    requestRender: (force?: boolean) => void;
    terminal: {
      write: (data: string) => void;
    };
  };

  let blurred = false;
  let activeTui: CursorTUI | undefined;
  let activeEditor: ModalEditorRuntime | undefined;

  // User preference from /setting "Show hardware cursor". Mirrors the value
  // that interactive-mode writes via tui.setShowHardwareCursor(). When false,
  // we leave the upstream fake inverse-video cursor intact (stripping it on
  // blur, restoring on focus) and skip all cursor-shape sequences.
  let userPrefersShowHardwareCursor = true;

  // Saved before we wrap setShowHardwareCursor / requestRender so our
  // internal blur/focus logic can toggle the effective visibility without
  // accidentally updating userPrefersShowHardwareCursor, and so session_shutdown
  // can restore the originals.
  let originalSetShowHardwareCursor: CursorTUI["setShowHardwareCursor"] | undefined;
  let originalRequestRender: CursorTUI["requestRender"] | undefined;

  // ANSI DECSCUSR cursor style sequences (CSI Ps SP q).
  // Pi's Editor always paints a fake inverse-video cursor in render()
  // (https://github.com/earendil-works/pi/blob/d06db09a53958e485131527db25c1293f29b9367/packages/tui/src/components/editor.ts#L466-L495).
  //
  // When the user enables hardware cursor, we keep only the zero-width
  // CURSOR_MARKER and drive the visible cursor with DECSCUSR shapes. Focus
  // tracking hides/shows the hardware cursor so the visible block no longer
  // depends on best-effort focus events.
  //
  // When the user disables hardware cursor, we leave the fake inverse-video
  // cursor intact (stripping it on blur, restoring on focus) and only emit
  // CURSOR_STYLE_RESET to clear any lingering cursor shape.
  const CURSOR_STYLE_INSERT = "\x1b[6 q"; // steady bar
  const CURSOR_STYLE_NORMAL = "\x1b[2 q"; // steady block
  const CURSOR_STYLE_RESET = "\x1b[0 q"; // reset to default

  function getCursorStyle(mode: Mode): string {
    return mode === "insert" ? CURSOR_STYLE_INSERT : CURSOR_STYLE_NORMAL;
  }

  /** Apply hardware cursor visibility based on user preference and current
   *  focus state. Uses the original setter to bypass the wrapper installed
   *  on tui.setShowHardwareCursor. */
  function applyHardwareCursorVisibility(tui: CursorTUI): void {
    if (!originalSetShowHardwareCursor) return;
    const effective = userPrefersShowHardwareCursor && !blurred;
    if (tui.getShowHardwareCursor?.() === effective) return;
    originalSetShowHardwareCursor.call(tui, effective);
  }

  /** Write the DECSCUSR shape if hardware cursor is active; otherwise emit
   *  CURSOR_STYLE_RESET so the terminal reverts to its default shape. */
  function writeCursorStyle(tui: CursorTUI, mode: Mode): void {
    tui.terminal.write(
      userPrefersShowHardwareCursor && !blurred ? getCursorStyle(mode) : CURSOR_STYLE_RESET,
    );
  }

  class PromptEditor extends ModalEditor {
    private readonly prefixColorizers: ModeColorizers;

    constructor(
      tui: any,
      theme: any,
      kb: any,
      labelColorizers: ModeColorizers | null,
      prefixColorizers: ModeColorizers,
    ) {
      super(tui, theme, kb, { labelColorizers, borderColorizers: null });
      this.prefixColorizers = prefixColorizers;
      // pi-vim v0.10.0+ has built-in cursor shape management
      // (https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts)
      // that conflicts with our DECSCUSR logic. Disable it so
      // our renderCursor() is the sole cursor authority.
      (this as any).cursorShapeRuntime = null;
    }

    override handleInput(data: string): void {
      // pi-vim has an ex command mode.
      // If active, let pi-vim handle input directly so remaps don't interfere.
      if ((this as unknown as ModalEditorRuntime).pendingExCommand !== null) {
        super.handleInput(data);
        return;
      }
      if (this.getMode() === "normal") {
        // pi-vim's cutCurrentLineContent (used by `cc`) relies on CTRL_A +
        // CTRL_K which doesn't work when autocomplete is active. Dismiss it
        // before executing a pending operator so `cc` clears correctly.
        if (
          (this as unknown as ModalEditorRuntime).pendingOperator !== null &&
          (this as any).isShowingAutocomplete?.()
        ) {
          (this as any).cancelAutocomplete?.();
        }

        // Backspace in normal mode: map to h (move left) instead of
        // passing through to the base Editor which deletes a character.
        if (matchesKey(data, Key.backspace)) {
          super.handleInput("h");
          return;
        }
        // React when Ctrl+C clears the input: auto-enter insert mode so
        // the user can start typing immediately.
        if (matchesKey(data, Key.ctrl("c"))) {
          super.handleInput(data);
          if (this.getText() === "") {
            (this as any).mode = "insert";
          }
          return;
        }
        // Single-key remaps (H -> 0, L -> $, U -> Ctrl+r)
        if (data in VIM_REMAPS) {
          super.handleInput(VIM_REMAPS[data]!);
          return;
        }
        // Y -> y$
        if (data === "Y") {
          super.handleInput("y");
          super.handleInput("$");
          return;
        }
        // cl -> s: pi-vim doesn't accept l as a motion for c, so we clear
        // the pending operator directly and delegate to the native s command.
        if ((this as unknown as ModalEditorRuntime).pendingOperator === "c" && data === "l") {
          (this as unknown as ModalEditorRuntime).pendingOperator = null;
          super.handleInput("s"); // cut char + insert
          return;
        }
      }
      super.handleInput(data);
    }

    override render(width: number): string[] {
      if (width <= PREFIX_WIDTH) {
        const lines = super.render(width);
        const bottomIdx = findBottomBorderIndex(lines);
        // Last line has ModalEditor's mode label; don't strip its inverse-video.
        this.renderCursor(lines, bottomIdx >= 1 ? bottomIdx : lines.length - 1);
        return lines;
      }

      // Related upstream logic:
      // - https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts (ModalEditor.render)
      // - https://github.com/badlogic/pi-mono/blob/e3fee7a511503ebe170223cd89e7631751539f25/packages/coding-agent/src/modes/interactive/components/custom-editor.ts
      //
      // Bypass ModalEditor.render() here so pi-vim does not append the mode
      // label to the last rendered line (which becomes the autocomplete list
      // during slash-command completion). We re-attach the label to the actual
      // bottom border below.
      const lines = CustomEditor.prototype.render.call(this, width - PREFIX_WIDTH) as string[];
      if (lines.length < 3) {
        this.renderCursor(lines, lines.length);
        return lines;
      }

      const bottomIdx = findBottomBorderIndex(lines);
      if (bottomIdx <= 0) {
        this.renderCursor(lines, lines.length);
        return lines;
      }

      const borderColor = this.borderColor ?? ((s: string) => s);
      const extraBorder = borderColor("─".repeat(PREFIX_WIDTH));
      const { raw: rawLabel, rendered: renderedLabel } = getRenderedModeLabel(
        this as unknown as ModalEditorRuntime,
      );
      const renderedPrefix = getRenderedPrefix(
        this as unknown as ModalEditorRuntime,
        this.prefixColorizers,
      );
      const labelWidth = visibleWidth(rawLabel);

      // The editor body is rendered `PREFIX_WIDTH` columns narrower so wrapped
      // text accounts for the prompt prefix. We then extend the top/bottom
      // borders back to the full terminal width and prefix only the body lines.
      lines[0] = lines[0]! + extraBorder;
      if (visibleWidth(lines[bottomIdx]!) >= labelWidth) {
        lines[bottomIdx] =
          truncateToWidth(lines[bottomIdx]!, width - PREFIX_WIDTH - labelWidth, "") +
          extraBorder +
          renderedLabel;
      } else {
        lines[bottomIdx] = lines[bottomIdx]! + extraBorder;
      }

      for (let i = 1; i < bottomIdx; i++) {
        lines[i] = (i === 1 ? renderedPrefix : CONTINUATION_PREFIX) + lines[i]!;
      }

      this.renderCursor(lines, bottomIdx);
      return lines;
    }

    private renderCursor(lines: string[], bottomIdx: number): void {
      if (userPrefersShowHardwareCursor) {
        // Optional: re-inject CURSOR_MARKER when Editor suppressed it
        // during autocomplete. Without it the cursor shape may revert to
        // steady block despite the correct DECSCUSR sequence being written.
        this.ensureCursorMarker(lines, bottomIdx);
        // Hardware cursor mode: strip the fake inverse-video cursor rendered
        // by Editor immediately after CURSOR_MARKER.
        this.stripFakeCursor(lines, bottomIdx);
      } else if (blurred) {
        // Fake cursor mode + blurred: same as hardware path — only the
        // software cursor adjacent to CURSOR_MARKER is stripped.
        this.stripFakeCursor(lines, bottomIdx);
      }
      // Fake cursor mode + focused: leave the upstream inverse-video cursor
      // untouched — it serves as the visible cursor.
    }

    /**
     * Re-inject CURSOR_MARKER when Editor suppressed it during autocomplete.
     * Without it the cursor shape falls back to steady block even though
     * the correct DECSCUSR sequence was written.
     */
    private ensureCursorMarker(lines: string[], bottomIdx: number): void {
      for (let i = bottomIdx - 1; i >= 1; i--) {
        if (lines[i]!.includes(CURSOR_MARKER)) return; // already present
      }
      // No marker found — inject before the first inverse-video sequence
      for (let i = bottomIdx - 1; i >= 1; i--) {
        const idx = lines[i]!.indexOf(SOFTWARE_CURSOR_START);
        if (idx !== -1) {
          lines[i] = lines[i]!.slice(0, idx) + CURSOR_MARKER + lines[i]!.slice(idx);
          return;
        }
      }
    }

    /**
     * Strip the fake inverse-video cursor rendered by Editor immediately
     * after CURSOR_MARKER, preserving the grapheme underneath. Delegates to
     * pi-vim's stripSoftwareCursorAfterMarker for exact alignment.
     * ensureCursorMarker guarantees MARKER is present before this runs.
     */
    private stripFakeCursor(lines: string[], bottomIdx: number): void {
      for (let i = bottomIdx - 1; i >= 1; i--) {
        const stripped = stripSoftwareCursorAfterMarker(lines[i]!);
        if (stripped !== lines[i]!) {
          lines[i] = stripped;
          return;
        }
      }
    }
  }

  const offMyFocusChange = pi.events.on("my:focus_change", (data: unknown) => {
    const { focused } = data as { focused: boolean };
    blurred = !focused;
    if (!activeTui || !activeEditor) return;

    if (userPrefersShowHardwareCursor) {
      applyHardwareCursorVisibility(activeTui);
      // Update cursor style on every focus change: writeCursorStyle
      // emits the DECSCUSR shape when focused and CURSOR_STYLE_RESET
      // when blurred, matching the setting-toggle path.
      writeCursorStyle(activeTui, activeEditor.getMode());
    } else {
      // Fake cursor mode: request a re-render so renderCursor() can
      // strip or restore the inverse-video cursor.
      activeTui.requestRender();
    }
  });

  pi.on("session_start", (_event, ctx) => {
    // https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts (default export session_start handler)
    const theme = ctx.ui.theme;
    const reverseVideo = (s: string) => `\x1b[7m${s}\x1b[27m`;
    const colorizers: ModeColorizers = {
      insert: (s: string) => theme.fg("borderMuted", reverseVideo(s)),
      normal: (s: string) => theme.fg("borderAccent", reverseVideo(s)),
      ex: (s: string) => theme.fg("warning", reverseVideo(s)),
    };
    // Prefix styling is intentionally lighter than the bottom mode label:
    // insert stays plain/default text, while normal gets only the accent fg.
    const prefixColorizers: ModeColorizers = {
      insert: (s: string) => s,
      normal: (s: string) => theme.fg("borderAccent", s),
      ex: (s: string) => theme.fg("warning", s),
    };

    setTimeout(() => {
      // Related upstream logic:
      // - https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts (default export session_start handler)
      // - https://github.com/badlogic/pi-mono/blob/cca5a3a1a4c6db90e4c5e2e95772845c1d5a251d/packages/coding-agent/src/modes/interactive/interactive-mode.ts#L1841-L1909 (setCustomEditorComponent)
      //
      // Defer until after pi-vim's own session_start handler has installed its
      // editor, then replace it with our prompt-editor subclass. interactive-mode
      // also copies borderColor from defaultEditor during the swap, so we
      // re-apply the thinking-level border color below.
      let editor: ModalEditorRuntime | undefined;

      applyPromptHistory(
        ctx,
        (history) => {
          ctx.ui.setEditorComponent((tui, editorTheme, kb) => {
            const newEditor = new PromptEditor(tui, editorTheme, kb, colorizers, prefixColorizers);

            // pi-vim v0.10.0+ configures quitFn and notifyFn on the editor
            // (https://github.com/lajarre/pi-vim/blob/fa62bb2/index.ts).
            // Apply them to our subclass so :q/:wq etc work correctly.
            (newEditor as any).setQuitFn(() => ctx.shutdown());
            (newEditor as any).setNotifyFn((message: string) => ctx.ui.notify(message, "warning"));

            activeTui = tui as CursorTUI;
            activeEditor = newEditor as unknown as ModalEditorRuntime;
            editor = activeEditor;

            // Capture initial user preference from the TUI. interactive-mode
            // passes settingsManager.getShowHardwareCursor() to the TUI
            // constructor, so this reflects the /setting value.
            userPrefersShowHardwareCursor = tui.getShowHardwareCursor?.() ?? true;

            // Capture the original setter once (unbound so .call(tui, …)
            // supplies the correct this). Guard against re-capture: if
            // session_shutdown didn't fire, the TUI still holds the
            // previous wrapper — skip to avoid nesting.
            if (!originalSetShowHardwareCursor) {
              originalSetShowHardwareCursor = tui.setShowHardwareCursor;
            }

            // Wrap setShowHardwareCursor to catch live /setting changes.
            // interactive-mode calls this when the user toggles
            // "Show hardware cursor".
            tui.setShowHardwareCursor = (enabled: boolean) => {
              const changed = enabled !== userPrefersShowHardwareCursor;
              userPrefersShowHardwareCursor = enabled;
              applyHardwareCursorVisibility(tui);
              // When switching away from hardware cursor, reset the
              // terminal cursor shape so it doesn't linger.
              if (!enabled) {
                tui.terminal.write(CURSOR_STYLE_RESET);
              } else if (!blurred) {
                writeCursorStyle(tui, newEditor.getMode());
              }
              if (changed) {
                tui.requestRender();
              }
            };

            // Apply initial effective visibility outside render() so
            // setShowHardwareCursor() cannot re-enter the render path.
            applyHardwareCursorVisibility(activeTui);
            // writeCursorStyle handles both modes (shape on enable, reset
            // on disable), but skip if user has hardware cursor off — no
            // DECSCUSR sequences needed at all.
            if (userPrefersShowHardwareCursor) {
              writeCursorStyle(activeTui, newEditor.getMode());
            }

            // Track mode changes to update cursor style. We hook into
            // requestRender (called by pi-vim after every handleInput that
            // mutates state) and write the appropriate shape sequence directly
            // to the terminal.
            // Guard against re-capture (same rationale as
            // originalSetShowHardwareCursor above).
            if (!originalRequestRender) {
              originalRequestRender = tui.requestRender;
            }
            const origRequestRender = originalRequestRender!;
            let lastShapeMode: Mode | undefined = newEditor.getMode();
            tui.requestRender = (force?: boolean) => {
              origRequestRender.call(tui, force);
              const curMode = newEditor.getMode();
              if (curMode !== lastShapeMode) {
                lastShapeMode = curMode;
                if (userPrefersShowHardwareCursor && !blurred) {
                  tui.terminal.write(getCursorStyle(curMode));
                }
              }
            };

            hydratePromptHistory(editor, history);
            return newEditor;
          });

          if (editor) {
            // Must run after setEditorComponent() returns: interactive-mode
            // overwrites newEditor.borderColor during the swap.
            editor.borderColor = ctx.ui.theme.getThinkingBorderColor(pi.getThinkingLevel());
          }
        },
        (history) => {
          if (!editor) return;
          replacePromptHistory(editor, history);
        },
      );
    }, 0);
  });

  pi.on("session_shutdown", () => {
    // Restore TUI methods that were wrapped in setEditorComponent so
    // subsequent calls from interactive-mode (applyRuntimeSettings,
    // resetExtensionUI) hit the originals instead of our stale closures.
    if (activeTui) {
      if (originalSetShowHardwareCursor) {
        activeTui.setShowHardwareCursor = originalSetShowHardwareCursor;
      }
      if (originalRequestRender) {
        activeTui.requestRender = originalRequestRender;
      }
    }
    offMyFocusChange();
    blurred = false;
    activeTui = undefined;
    activeEditor = undefined;
    userPrefersShowHardwareCursor = true;
    originalSetShowHardwareCursor = undefined;
    originalRequestRender = undefined;
    // Restore default terminal cursor style on exit
    process.stdout.write(CURSOR_STYLE_RESET);
  });
}
