# https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

# https://github.com/folke/dot/blob/56d310467f3f962e506810b710a1562cee03b75e/config/starship.toml
[custom.shell]
command = "echo $STARSHIP_SHELL"                                                # shows output of command
when = """ test "$STARSHIP_SHELL" != "" && test "$STARSHIP_SHELL" != "fish" """ # check "" for Rolv-Apneseth/starship.yazi
style = "dimmed blue"
format = "[$output]($style)"
shell = ["bash"]

# https://github.com/Sonico98/yazi-prompt.sh#starship
[custom.yazi]
command = """ [[ "$YAZI_LEVEL" == "1" ]] && echo "" || echo "$YAZI_LEVEL" """
symbol = "󰇥"
when = """ test -n "$YAZI_LEVEL" """
style = "bright-yellow"
format = "[$symbol $output ]($style)"
shell = ["bash"]

# [custom.neovim]
# command = 'bob ls | rg Used | awk "{print \$2}"' # shows output of command
# detect_folders = ["lua"]
# style = "green"
# format = "[ $output ]($style)"
# shell = ["bash"]

[git_branch]
symbol = " "
format = '[$branch(:$remote_branch)]($style) '

# https://github.com/folke/snacks.nvim/blob/7964f040bf605b2a3e8d66d02c453469352e005e/lua/snacks/picker/source/git.lua#L412-L468
[git_status]
untracked = '[?$count](bold blue) '
staged = '[++$count](bold green) '
stashed = "[ ](cyan) "
deleted = '[D$count](bold red) '
modified = '[M$count](bold yellow) '
renamed = '[R$count](bold 136) '
conflicted = '[!$count](bold red) '
behind = '[⇣${count}](bold purple) '
ahead = '[⇡${count}](bold purple) '
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](bold purple) '
format = '([$all_status$ahead_behind]($style))'

[git_metrics]
disabled = false

# [mise]
# disabled = false
# healthy_symbol = ""

# starship preset nerd-font-symbols -o ~/.config/starship.toml
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
